version: "3"

services:
  monitoring:
    ports:
        - 16241:16241
    stdin_open: true
    tty: true
    uts: host
    container_name: yc-monitoring
    restart: always
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "100m"
    volumes:
        - /proc:/ua_proc
#        - /full/path/to/conf.d/<имя конфиг файла>.yml:/etc/yandex/unified_agent/conf.d/<имя конфиг файла>.yml
    environment:
        - PROC_DIRECTORY=/ua_proc
        - FOLDER_ID=b1g36jep2lo1jbar61ci
    image: cr.yandex/yc/unified-agent
