version: '3'

services:
  pushgateway:
    image: prom/pushgateway
#    network_mode: host
    ports:
      - 9091:9091
    container_name: push-gateway
    restart: unless-stopped
    environment:
      TZ: "Europe/Moscow"
