version: '3'

services:
  prometheus:
    image: prom/prometheus:latest
    network_mode: host
    volumes:
      - ./prometheus:/etc/prometheus/
    container_name: prometheus
    hostname: prometheus
    command:
      - --config.file=/etc/prometheus/prometheus.yml
      - --web.enable-admin-api
#    ports:
#      - 9090:9090
    restart: unless-stopped
    environment:
      TZ: "Europe/Moscow"
#    networks:
#      - default

  grafana:
    image: grafana/grafana
    network_mode: host
    user: root
    depends_on:
      - prometheus
#    ports:
#      - 3001:3000
    volumes:
      - ./grafana:/var/lib/grafana
      - ./grafana/provisioning/:/etc/grafana/provisioning/
    container_name: grafana
    hostname: grafana
    restart: unless-stopped
    environment:
      TZ: "Europe/Moscow"
      GF_SERVER_DOMAIN: "mon.e-comet.io"
      GF_SERVER_ROOT_URL: "%(protocol)s://%(domain)s/grafana/"
      GF_SERVER_SERVE_FROM_SUB_PATH: true

  blackbox-exporter:
    network_mode: host
    container_name: blackbox_exporter
    restart: unless-stopped
    volumes:
      - ./blackbox:/config
    image: prom/blackbox-exporter
    command:
    - --config.file=/config/blackbox.yml

networks:
  default:
