groups:

- name: prometheus

  rules:

    - alert: items<1000
      expr: 'last_over_time(items{service="feedbacks_scrapper"}[10m]) = my_metric != bool 0'
      for: 1h
      labels:
        severity: warning
      annotations:
        summary: feedback scrapers is less < 1000 (instance {{ $labels.instance }})
        description: "feedback scrapers is less < 1000\n  VALUE = {{ $value }}\n  LABELS = {{ $labels }}"