groups:

- name: scrapers_mem_usage

  rules:

    - alert: feedback scrapers memory usage increased
      expr: rate((memory_usage{service="feedbacks_scrapper", type="vms"}[5m]))*100 > 100
      for: 10m
      labels:
        severity: warning
      annotations:
        summary: feedback scrapers memory usage increased on more than 100% for 10 min (instance {{ $labels.instance }})
        description: "feedback scrapers memory usage increased on more than 100%  < 1000\n  VALUE = {{ $value }}\n  LABELS = {{ $labels }}"

    - alert: accounts_products memory usage increase on 1000%
      expr:  rate((memory_usage{service="accounts_products", type="vms"}[5m]))*100 > 1000
      for: 5m
      labels:
        severity: warning
      annotations:
        summary: accounts_products memory usage increased on more than 1000% (instance {{ $labels.instance }})
        description: "accounts_products memory usage increased on more than 1000% \n  VALUE = {{ $value }}\n  LABELS = {{ $labels }}"

    - alert: adverts memory usage increased in 7 times
      expr: rate((memory_usage{service="adverts", type="vms"}[5m]))*100 > 700
      for: 0m
      labels:
        severity: warning
      annotations:
        summary: adverts is experience memory usage increase (instance {{ $labels.instance }})
        description: "adverts is experience memory usage increase\n  VALUE = {{ $value }}\n  LABELS = {{ $labels }}"

    - alert: auctions_0 mem usage is increased 50 times
      expr: rate((memory_usage{service="auctions_0", type="vms"}[5m]))*100 > 5557
      for: 0m
      labels:
        severity: warning
      annotations:
        summary: auctions_0 mem usage increases 50 times(instance {{ $labels.instance }})
        description: "auctions_0 mem usage\n  VALUE = {{ $value }}\n  LABELS = {{ $labels }}"

    - alert: auctions_1 mem usage increased more than 30 times
      expr: rate((memory_usage{service="auctions_1", type="vms"}[5m]))*100 > 3000
      for: 5m
      labels:
        severity: warning
      annotations:
        summary: auctions_1 mem usage increased more than 30 times (instance {{ $labels.instance }})
        description: "auctions_1 mem usage increased more than 30 times\n  VALUE = {{ $value }}\n  LABELS = {{ $labels }}"

    - alert: autopilot mem usage icrease for 24h
      expr: rate((memory_usage{service="autopilot", type="vms"}[5m]))*100 > 100
      for: 24h
      labels:
        severity: warning
      annotations:
        summary: autopilot mem usage icrease for 24h twice (instance {{ $labels.instance }})
        description: "autopilot mem usage icrease for 24h\n  VALUE = {{ $value }}\n  LABELS = {{ $labels }}"

    - alert: balances rate >35
      expr: rate((memory_usage{service="balances", type="vms"}[1m]))*100 > 35
      for: 5m
      labels:
        severity: warning
      annotations:
        summary: balances is less < 30 (instance {{ $labels.instance }})
        description: "balances is less < 1000\n  VALUE = {{ $value }}\n  LABELS = {{ $labels }}"

    - alert: bidder memory usage increase 10x
      expr: rate((memory_usage{service="bidder", type="vms"}[1m]))*100 > 1000
      for: 30m
      labels:
        severity: warning
      annotations:
        summary: bidder memory usage increase 10x (instance {{ $labels.instance }})
        description: "bidder memory usage increase 10x\n  VALUE = {{ $value }}\n  LABELS = {{ $labels }}"

    - alert: budgets mem usage 2x increase
      expr: rate((memory_usage{service="budgets", type="vms"}[5m]))*100 > 200
      for: 3m
      labels:
        severity: warning
      annotations:
        summary: budgets mem usage 2x increase(instance {{ $labels.instance }})
        description: "budgets mem usage 2x increase\n  VALUE = {{ $value }}\n  LABELS = {{ $labels }}"
  
    - alert: campaigns mem usage 30x increase 
      expr: rate((memory_usage{service="campaigns", type="vms"}[10m]))*100 > 3000
      for: 10m
      labels:
        severity: warning
      annotations:
        summary: campaigns mem usage 30x increase (instance {{ $labels.instance }})
        description: "campaigns mem usage 30x increase\n  VALUE = {{ $value }}\n  LABELS = {{ $labels }}"

    - alert: campaigns_expenses mem usage inc
      expr: rate((memory_usage{service="campaigns_expenses", type="vms"}[10m]))*100 > 100
      for: 2h
      labels:
        severity: warning
      annotations:
        summary: campaigns_expenses mem usage increased (instance {{ $labels.instance }})
        description: "campaigns_expenses mem usage increased \n  VALUE = {{ $value }}\n  LABELS = {{ $labels }}"

    - alert: feedbacks_uploader items<1
      expr: rate((memory_usage{service="feedbacks_uploader", type="vms"}[1m]))*100 > 35
      for: 2h
      labels:
        severity: warning
      annotations:
        summary: feedbacks_uploader is less < 1 (instance {{ $labels.instance }})
        description: "feedbacks_uploader is less < 1\n  VALUE = {{ $value }}\n  LABELS = {{ $labels }}"

    - alert: orders_scrapper items<10000
      expr: rate((memory_usage{service="orders_scrapper", type="vms"}[1h]))*100 > 1000
      for: 30m
      labels:
        severity: warning
      annotations:
        summary: orders_scrapper is less < 10000 (instance {{ $labels.instance }})
        description: "orders_scrapper is less < 10000\n  VALUE = {{ $value }}\n  LABELS = {{ $labels }}"

    - alert: stocks_scrapper items<10000
      expr: rate((memory_usage{service="stocks_scrapper", type="vms"}[5m]))*100 > 1000
      for: 30m
      labels:
        severity: warning
      annotations:
        summary: stocks_scrapper is less < 10000 (instance {{ $labels.instance }})
        description: "stocks_scrapper is less < 10000\n  VALUE = {{ $value }}\n  LABELS = {{ $labels }}"

    - alert: ad_stats's errors >1
      expr: rate((memory_usage{service="ad_stats"}[5m]))*100 > 300
      for: 30m
      labels:
        severity: warning
      annotations:
        summary: ad_statshas errors < 1000 (instance {{ $labels.instance }})
        description: "ad_stats has errors < 1000\n  VALUE = {{ $value }}\n  LABELS = {{ $labels }}"

    - alert: phrases_positons's errors >1
      expr: rate((memory_usage{service="phrases_positions"}[5m]))*100 > 100
      for: 0m
      labels:
        severity: warning
      annotations:
        summary: phrases_positons has errors (instance {{ $labels.instance }})
        description: "phrases_positons has errors\n  VALUE = {{ $value }}\n  LABELS = {{ $labels }}"
  
    - alert: phrases_positons_full's errors >1
      expr: rate((memory_usage{service="phrases_positions_full"}[1m]))*100 > 100
      for: 5m
      labels:
        severity: warning
      annotations:
        summary: phrases_positons_full has errors (instance {{ $labels.instance }})
        description: "phrases_positons_full has errors \n  VALUE = {{ $value }}\n  LABELS = {{ $labels }}"

    - alert: positions's items errors >1
      expr: 'increase(errors{job="vps", service="positions"}[1m]) > 1'
      for: 6h
      labels:
        severity: warning
      annotations:
        summary: positionshas has errors  (instance {{ $labels.instance }})
        description: "positions has errors \n  VALUE = {{ $value }}\n  LABELS = {{ $labels }}"

    - alert: remainders's errors >1
      expr: rate((memory_usage{service="remainders", type="vms"}[20m]))*100 > 2000
      for: 6h
      labels:
        severity: warning
      annotations:
        summary: remainders has errors  (instance {{ $labels.instance }})
        description: "remainders has errors \n  VALUE = {{ $value }}\n  LABELS = {{ $labels }}"

    - alert: seller's errors >1
      expr: 'increase(errors{job="vps", service="sellers"}[1m]) > 1'
      for: 6h
      labels:
        severity: warning
      annotations:
        summary: sellers has errors (instance {{ $labels.instance }})
        description: "sellers has errors \n  VALUE = {{ $value }}\n  LABELS = {{ $labels }}"

    - alert: stat_words's errors >1
      expr: rate((memory_usage{service="stat_words", type="vms"}[20m]))*100 > 10000
      for: 30m
      labels:
        severity: warning
      annotations:
        summary: stat_words has errors (instance {{ $labels.instance }})
        description: "stat_words has errors \n  VALUE = {{ $value }}\n  LABELS = {{ $labels }}"

    - alert: wb_api_service's errors >1
      expr: rate((memory_usage{service="wb_api_service", type="vms"}[20m]))*100 > 400
      for: 30m
      labels:
        severity: warning
      annotations:
        summary: wb_api_service has errors < 20000 (instance {{ $labels.instance }})
        description: "wb_api_service has errors < 2000\n  VALUE = {{ $value }}\n  LABELS = {{ $labels }}"

    - alert: wb_service's errors >1
      expr: rate((memory_usage{service="wb_service", type="vms"}[5m]))*100 > 100
      for: 1h
      labels:
        severity: warning
      annotations:
        summary: wb_service has errors (instance {{ $labels.instance }})
        description: "wb_service has errors \n  VALUE = {{ $value }}\n  LABELS = {{ $labels }}"


