groups:

- name: scrapers_failures

  rules:

    - alert: bidder failures<1000
      expr: 'increase(request_failures{service="bidder"}[1m]) < 1000'
      for: 1h
      labels:
        severity: warning
      annotations:
        summary: feedback scrapers is less < 1000 (instance {{ $labels.instance }})
        description: "feedback scrapers is less < 1000\n  VALUE = {{ $value }}\n  LABELS = {{ $labels }}"

    - alert: accounts_products failures<1300
      expr: 'increase(request_failures{service="accounts_product"}[1m]) < 1300'
      for: 1h
      labels:
        severity: warning
      annotations:
        summary: accounts_products is less < 1300 (instance {{ $labels.instance }})
        description: "accounts_products is less < 1000\n  VALUE = {{ $value }}\n  LABELS = {{ $labels }}"

    - alert: adverts failures is increasing
      expr: 'increase(request_failures{service="adverts"}[1m]) < 1300'
      for: 30m
      labels:
        severity: warning
      annotations:
        summary: adverts failures < 1300 (instance {{ $labels.instance }})
        description: "adverts is less < 1000\n  VALUE = {{ $value }}\n  LABELS = {{ $labels }}"

    - alert: auctions_0 failures
      expr: 'increase(request_failures{service="auctions_0"}[1m]) < 1000'
      for: 15m
      labels:
        severity: warning
      annotations:
        summary: auctions_0 failures (instance {{ $labels.instance }})
        description: "auctions_0 failures\n  VALUE = {{ $value }}\n  LABELS = {{ $labels }}"

    - alert: auctions_1 
      expr: 'increase(request_failures{service="bidder"}[1m]) < 1000'
      for: 1h
      labels:
        severity: warning
      annotations:
        summary: auctions_1 is less < 1000 (instance {{ $labels.instance }})
        description: "auctions_1 is less < 1000\n  VALUE = {{ $value }}\n  LABELS = {{ $labels }}"

    - alert: autopilot failures<1000 for 24h
      expr: 'increase(request_failures{service="bidder"}[1m]) < 1000'
      for: 24h
      labels:
        severity: warning
      annotations:
        summary: autopilot is less < 1000 (instance {{ $labels.instance }})
        description: "autopilot is less < 1000\n  VALUE = {{ $value }}\n  LABELS = {{ $labels }}"

    - alert: balances failures<30
      expr: 'increase(request_failures{service="bidder"}[1m]) < 1000'
      for: 30m
      labels:
        severity: warning
      annotations:
        summary: balances is less < 30 (instance {{ $labels.instance }})
        description: "balances is less < 1000\n  VALUE = {{ $value }}\n  LABELS = {{ $labels }}"

    - alert: bidder failures<30
      expr: 'increase(request_failures{service="bidder"}[1m]) < 1000'
      for: 30m
      labels:
        severity: warning
      annotations:
        summary: bidder is less < 30 (instance {{ $labels.instance }})
        description: "bidder is less < 1000\n  VALUE = {{ $value }}\n  LABELS = {{ $labels }}"

    - alert: budgets failures<100
      expr: 'increase(request_failures{service="bidder"}[1m]) < 1000'
      for: 30m
      labels:
        severity: warning
      annotations:
        summary: budgets is less < 30 (instance {{ $labels.instance }})
        description: "budgets is less < 1000\n  VALUE = {{ $value }}\n  LABELS = {{ $labels }}"
  
    - alert: campaigns failures< 100
      expr: 'increase(request_failures{service="bidder"}[1m]) < 1000'
      for: 30m
      labels:
        severity: warning
      annotations:
        summary: campaigns is less < 100 (instance {{ $labels.instance }})
        description: "campaigns is less < 1000\n  VALUE = {{ $value }}\n  LABELS = {{ $labels }}"

    - alert: campaigns_expenses failures<10000
      expr: 'increase(request_failures{service="bidder"}[1m]) < 1000'
      for: 30m
      labels:
        severity: warning
      annotations:
        summary: campaigns_expenses is less < 10000 (instance {{ $labels.instance }})
        description: "campaigns_expenses is less < 1000\n  VALUE = {{ $value }}\n  LABELS = {{ $labels }}"

    - alert: feedbacks_uploader failures<1
      expr: 'increase(request_failures{service="bidder"}[1m]) < 1000'
      for: 2h
      labels:
        severity: warning
      annotations:
        summary: feedbacks_uploader is less < 1 (instance {{ $labels.instance }})
        description: "feedbacks_uploader is less < 1\n  VALUE = {{ $value }}\n  LABELS = {{ $labels }}"

    - alert: orders_scrapper failures<10000
      expr: 'increase(request_failures{service="bidder"}[1m]) < 1000'
      for: 30m
      labels:
        severity: warning
      annotations:
        summary: orders_scrapper is less < 10000 (instance {{ $labels.instance }})
        description: "orders_scrapper is less < 10000\n  VALUE = {{ $value }}\n  LABELS = {{ $labels }}"

    - alert: stocks_scrapper failures<10000
      expr: 'increase(request_failures{service="bidder"}[1m]) < 1000'
      for: 30m
      labels:
        severity: warning
      annotations:
        summary: stocks_scrapper is less < 10000 (instance {{ $labels.instance }})
        description: "stocks_scrapper is less < 10000\n  VALUE = {{ $value }}\n  LABELS = {{ $labels }}"

    - alert: add_phrases_presets errors >1
      expr: 'increase(request_failures{service="bidder"}[1m]) < 1000'
      for: 30m
      labels:
        severity: warning
      annotations:
        summary: add_phrases_presetshas errors < 10000 (instance {{ $labels.instance }})
        description: "add_phrases_presets has errors < 10000\n  VALUE = {{ $value }}\n  LABELS = {{ $labels }}"

    - alert: ad_stats's errors >1
      expr: 'increase(request_failures{job="vps", service="phrases_positons"}[1m]) < 1000'
      for: 30m
      labels:
        severity: warning
      annotations:
        summary: ad_statshas errors < 1000 (instance {{ $labels.instance }})
        description: "ad_stats has errors < 1000\n  VALUE = {{ $value }}\n  LABELS = {{ $labels }}"

    - alert: phrases_positons's errors >1
      expr: 'increase(request_failures{job="vps", service="phrases_positons"}[1m]) < 1000'
      for: 6h
      labels:
        severity: warning
      annotations:
        summary: phrases_positons has errors (instance {{ $labels.instance }})
        description: "phrases_positons has errors\n  VALUE = {{ $value }}\n  LABELS = {{ $labels }}"
  
    - alert: phrases_positons_full's errors >1
      expr: 'increase(request_failures{job="vps", service="phrases_positons"}[1m]) < 1000'
      for: 6h
      labels:
        severity: warning
      annotations:
        summary: phrases_positons_full has errors (instance {{ $labels.instance }})
        description: "phrases_positons_full has errors \n  VALUE = {{ $value }}\n  LABELS = {{ $labels }}"

    - alert: positions's failures errors >1
      expr: 'increase(request_failures{job="vps", service="phrases_positons"}[1m]) < 1000'
      for: 6h
      labels:
        severity: warning
      annotations:
        summary: positionshas has errors  (instance {{ $labels.instance }})
        description: "positions has errors \n  VALUE = {{ $value }}\n  LABELS = {{ $labels }}"

    - alert: remainders's errors >1
      expr: 'increase(request_failures{job="vps", service="phrases_positons"}[1m]) < 1000'
      for: 6h
      labels:
        severity: warning
      annotations:
        summary: remainders has errors  (instance {{ $labels.instance }})
        description: "remainders has errors \n  VALUE = {{ $value }}\n  LABELS = {{ $labels }}"

    - alert: seller's errors >1
      expr: 'increase(request_failures{job="vps", service="phrases_positons"}[1m]) < 1000'
      for: 6h
      labels:
        severity: warning
      annotations:
        summary: sellers has errors (instance {{ $labels.instance }})
        description: "sellers has errors \n  VALUE = {{ $value }}\n  LABELS = {{ $labels }}"

    - alert: stat_words's errors >1
      expr: 'increase(request_failures{job="vps", service="phrases_positons"}[1m]) < 1000'
      for: 30min
      labels:
        severity: warning
      annotations:
        summary: stat_words has errors (instance {{ $labels.instance }})
        description: "stat_words has errors \n  VALUE = {{ $value }}\n  LABELS = {{ $labels }}"

    - alert: wb_api_service's errors >1
      expr: 'increase(request_failures{job="vps", service="phrases_positons"}[1m]) < 1000'
      for: 30min
      labels:
        severity: warning
      annotations:
        summary: wb_api_service has errors < 20000 (instance {{ $labels.instance }})
        description: "wb_api_service has errors < 2000\n  VALUE = {{ $value }}\n  LABELS = {{ $labels }}"

    - alert: wb_service's errors >1
      expr: 'increase(request_failures{job="vps", service="phrases_positons"}[1m]) < 1000'
      for: 24h
      labels:
        severity: warning
      annotations:
        summary: wb_service has errors (instance {{ $labels.instance }})
        description: "wb_service has errors \n  VALUE = {{ $value }}\n  LABELS = {{ $labels }}"


