groups:

- name: scrapers_request_latency

  rules:

    - alert: items<1000
      expr: rate(request_latency_bucket{service="feedbacks_scrapper"}[10m])*100 > 1000
      for: 1h
      labels:
        severity: warning
      annotations:
        summary: feedback scrapers is less < 1000 (instance {{ $labels.instance }})
        description: "feedback scrapers is less < 1000\n  VALUE = {{ $value }}\n  LABELS = {{ $labels }}"

    - alert: accounts_products items<1300
      expr: rate(request_latency_bucket{service="accounts_products"}[10m])*100 > 1000
      for: 5m
      labels:
        severity: warning
      annotations:
        summary: accounts_products is less < 1300 (instance {{ $labels.instance }})
        description: "accounts_products is less < 1000\n  VALUE = {{ $value }}\n  LABELS = {{ $labels }}"

    - alert: adverts items<1000
      expr: rate(request_latency_bucket{service="adverts"}[10m])*100 > 1000
      for: 30m
      labels:
        severity: warning
      annotations:
        summary: adverts is less < 1000 (instance {{ $labels.instance }})
        description: "adverts is less < 1000\n  VALUE = {{ $value }}\n  LABELS = {{ $labels }}"

    - alert: auctions_0 items<100000
      expr: rate(request_latency_bucket{service="auctions_0"}[10m])*100 > 1000
      for: 15m
      labels:
        severity: warning
      annotations:
        summary: auctions_0 is less < 100000 (instance {{ $labels.instance }})
        description: "auctions_0 is less < 1000\n  VALUE = {{ $value }}\n  LABELS = {{ $labels }}"

    - alert: auctions_1 items<100000
      expr: rate(request_latency_bucket{service="auctions_1"}[10m])*100 > 1000
      for: 1h
      labels:
        severity: warning
      annotations:
        summary: auctions_1 is less < 1000 (instance {{ $labels.instance }})
        description: "auctions_1 is less < 1000\n  VALUE = {{ $value }}\n  LABELS = {{ $labels }}"

    - alert: autopilot items<1000 for 24h
      expr: rate(request_latency_bucket{service="autopilot"}[10m])*100 > 1000
      for: 24h
      labels:
        severity: warning
      annotations:
        summary: autopilot is less < 1000 (instance {{ $labels.instance }})
        description: "autopilot is less < 1000\n  VALUE = {{ $value }}\n  LABELS = {{ $labels }}"

    - alert: balances items<30
      expr: rate(request_latency_bucket{service="balances"}[10m])*100 > 1000
      for: 30m
      labels:
        severity: warning
      annotations:
        summary: balances is less < 30 (instance {{ $labels.instance }})
        description: "balances is less < 1000\n  VALUE = {{ $value }}\n  LABELS = {{ $labels }}"

    - alert: bidder items<30
      expr: rate(request_latency_bucket{service="bidder"}[10m])*100 > 1000
      for: 5m
      labels:
        severity: warning
      annotations:
        summary: bidder is less < 30 (instance {{ $labels.instance }})
        description: "bidder is less < 1000\n  VALUE = {{ $value }}\n  LABELS = {{ $labels }}"

    - alert: budgets items<100
      expr: rate(request_latency_bucket{service="budget"}[10m])*100 > 1000
      for: 30m
      labels:
        severity: warning
      annotations:
        summary: budgets is less < 30 (instance {{ $labels.instance }})
        description: "budgets is less < 1000\n  VALUE = {{ $value }}\n  LABELS = {{ $labels }}"
  
    - alert: campaigns items< 100
      expr: rate(request_latency_bucket{service="campaingns"}[10m])*100 > 1000
      for: 30m
      labels:
        severity: warning
      annotations:
        summary: campaigns is less < 100 (instance {{ $labels.instance }})
        description: "campaigns is less < 1000\n  VALUE = {{ $value }}\n  LABELS = {{ $labels }}"

    - alert: campaigns_expenses items<10000
      expr: 'last_over_time(items{service="campaigns_expenses"}[10m]) < 10000'
      for: 30m
      labels:
        severity: warning
      annotations:
        summary: campaigns_expenses is less < 10000 (instance {{ $labels.instance }})
        description: "campaigns_expenses is less < 1000\n  VALUE = {{ $value }}\n  LABELS = {{ $labels }}"

    - alert: feedbacks_uploader items<1
      expr: rate(request_latency_bucket{service="feedbacks_uploader"}[10m])*100 > 1000
      for: 2h
      labels:
        severity: warning
      annotations:
        summary: feedbacks_uploader is less < 1 (instance {{ $labels.instance }})
        description: "feedbacks_uploader is less < 1\n  VALUE = {{ $value }}\n  LABELS = {{ $labels }}"

    - alert: orders_scrapper items<10000
      expr: rate(request_latency_bucket{service="orders_scrapper"}[10m])*100 > 1000
      for: 30m
      labels:
        severity: warning
      annotations:
        summary: orders_scrapper is less < 10000 (instance {{ $labels.instance }})
        description: "orders_scrapper is less < 10000\n  VALUE = {{ $value }}\n  LABELS = {{ $labels }}"

    - alert: stocks_scrapper items<10000
      expr: rate(request_latency_bucket{service="stocks_scrapper"}[10m])*100 > 1000
      for: 30m
      labels:
        severity: warning
      annotations:
        summary: stocks_scrapper is less < 10000 (instance {{ $labels.instance }})
        description: "stocks_scrapper is less < 10000\n  VALUE = {{ $value }}\n  LABELS = {{ $labels }}"

    - alert: ad_stats's errors >1
      expr: rate(request_latency_bucket{service="ad_stats"}[10m])*100 > 1000
      for: 30m
      labels:
        severity: warning
      annotations:
        summary: ad_statshas errors < 1000 (instance {{ $labels.instance }})
        description: "ad_stats has errors < 1000\n  VALUE = {{ $value }}\n  LABELS = {{ $labels }}"

    - alert: phrases_positons's errors >1
      expr: rate(request_latency_bucket{service="phrases_postions"}[10m])*100 > 1000'
      for: 1h
      labels:
        severity: warning
      annotations:
        summary: phrases_positons has errors (instance {{ $labels.instance }})
        description: "phrases_positons has errors\n  VALUE = {{ $value }}\n  LABELS = {{ $labels }}"

    - alert: phrases_positons_full's errors >1
      expr: rate(request_latency_bucket{service="phrases_postions_full"}[10m])*100 > 1000'
      for: 6h
      labels:
        severity: warning
      annotations:
        summary: phrases_positons_full has errors (instance {{ $labels.instance }})
        description: "phrases_positons_full has errors \n  VALUE = {{ $value }}\n  LABELS = {{ $labels }}"

    - alert: positions's items errors >1
      expr: rate(request_latency_bucket{service="positions"}[10m])*100 > 1000'
      for: 6h
      labels:
        severity: warning
      annotations:
        summary: positionshas has errors  (instance {{ $labels.instance }})
        description: "positions has errors \n  VALUE = {{ $value }}\n  LABELS = {{ $labels }}"

    - alert: remainders's errors >1
      expr: rate(request_latency_bucket{service="remainders"}[10m])*100 > 1000'
      for: 6h
      labels:
        severity: warning
      annotations:
        summary: remainders has errors  (instance {{ $labels.instance }})
        description: "remainders has errors \n  VALUE = {{ $value }}\n  LABELS = {{ $labels }}"

    - alert: seller's errors >1
      expr: rate(request_latency_bucket{service="sellers"}[10m])*100 > 1000'
      for: 6h
      labels:
        severity: warning
      annotations:
        summary: sellers has errors (instance {{ $labels.instance }})
        description: "sellers has errors \n  VALUE = {{ $value }}\n  LABELS = {{ $labels }}"

    - alert: stat_words's errors >1
      expr: rate(request_latency_bucket{service="stats_words"}[10m])*100 > 1000'
      for: 30m
      labels:
        severity: warning
      annotations:
        summary: stat_words has errors (instance {{ $labels.instance }})
        description: "stat_words has errors \n  VALUE = {{ $value }}\n  LABELS = {{ $labels }}"

    - alert: wb_api_service's errors >1
      expr: rate(request_latency_bucket{service="wb_api_service"}[10m])*100 > 1000'
      for: 30m
      labels:
        severity: warning
      annotations:
        summary: wb_api_service has errors < 20000 (instance {{ $labels.instance }})
        description: "wb_api_service has errors < 2000\n  VALUE = {{ $value }}\n  LABELS = {{ $labels }}"

    - alert: wb_service's errors >1
      expr: rate(request_latency_bucket{service="wb_service"}[10m])*100 > 1000'
      for: 24h
      labels:
        severity: warning
      annotations:
        summary: wb_service has errors (instance {{ $labels.instance }})
        description: "wb_service has errors \n  VALUE = {{ $value }}\n  LABELS = {{ $labels }}"