# alertmanager.yml

route:
  receiver: default
  routes:
    - matchers:
        - severity="warning"
      receiver: slack
receivers:
  - name: slack
    slack_configs:
      - channel: "#monitoring"
        send_resolved: true
        api_url: "https://hooks.slack.com/services/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"
        title: Alert
        text: >-
          {{ range .Alerts -}}
          *Alert:* {{ .Annotations.title }}{{ if .Labels.severity }} - `{{ .Labels.severity }}`{{ end }}
          *Description:* {{ .Annotations.description }}
          *Details:*
            {{ range .Labels.SortedPairs }} • *{{ .Name }}:* `{{ .Value }}`
            {{ end }}
          {{ end }}
  - name: default