version: '3'

services:
  alert-manager:
    image: prom/alertmanager
    volumes:
      - ./alertmanager.yml:/etc/alertmanager/alertmanager.yml
    # networks:
    #   - localprom
    ports:
      - 127.0.0.1:9093:9093