modules:
  http_2xx:
    prober: http
    http:
      preferred_ip_protocol: "ip4" # defaults to "ip6"
  http_post_2xx:
    prober: http
    http:
      method: POST
      preferred_ip_protocol: "ip4" # defaults to "ip6"
  tcp_connect:
    prober: tcp
